future: true
permalink: /blog/:categories/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "my-site"
      category: ppoo
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project" # overrides previous default layout
      author: "Black pants"
      category: papa
